Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ClothingStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return RedirectToAction("Index", "Statistics");
        }
    }
}

Controllers/HomeController.cs
using ClothingStore.Models;
using ClothingStore.Models.Entity;
using ClothingStore.Models.Service.product;
using ClothingStore.Models.Service.wishlist;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using ClothingStore.Models.Helper;
using Microsoft.AspNetCore.Authorization;

namespace ClothingStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly IProductService _productService;
        private readonly IWishlistService _wishlistService;
        private readonly UserManager<User> _userManager;

        public HomeController(IProductService productService,IWishlistService wishlistService, UserManager<User> userManager)
        {
            _productService = productService;
            _wishlistService = wishlistService;
            _userManager = userManager;
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> Index()
        { 
         
            if (HttpContext.Session.GetObjectFromJson<IEnumerable<Wishlist>>("Wishlists") == null)
            {
                var user = await _userManager.GetUserAsync(User);
                var wishlists = await _wishlistService.GetAllAsync(user.Id);
                HttpContext.Session.SetObjectAsJson("Wishlists", wishlists);
            }

            var productsHome = await _productService.GetAllAsync();

            return View(productsHome);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Controllers/ProductController.cs
using ClothingStore.Models.Entity;
using ClothingStore.Models.Helper;
using ClothingStore.Models.Service.product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace ClothingStore.Controllers
{
    [Authorize(Roles = "User")]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly UserManager<User> _userManager;
        public ProductController(IProductService productService, UserManager<User> userManager)
        {
            _productService = productService;
            _userManager = userManager;
        }

        
        public IActionResult Index()
        {
            return View();
        }

        
        public async Task<IActionResult> Detail(int productId)
        {
            var product = await _productService.GetByIdAsync(productId);
            return View("Detail", product);
        }

        
        public async Task<IActionResult> RedirectToProductsView(string gender, string category)
        {
            var products = await _productService.GetProductByCategoryName(category);
            if(gender != null)
            {
                products = products.Where(i => i.Gender.Equals(gender)).ToList();
            }

            HttpContext.Session.SetObjectAsJson("RedirectProducts", products);

            return View("Index", products);
        }

        
        [HttpPost]
        public async Task<IActionResult> SortBy(string sortBy = "")
        {
            var products = HttpContext.Session.GetObjectFromJson<IEnumerable<Product>>("RedirectProducts"); ;
            switch (sortBy)
            {
                case "PriceDesc":
                    products = products.OrderByDescending(i => i.UnitPrice);
                    break;
                case "PriceAsc":
                    products = products.OrderBy(i => i.UnitPrice);
                    break;
                case "NameDesc":
                    products = products.OrderByDescending(i => i.Name);
                    break;
                case "NameAsc":
                    products = products.OrderBy(i => i.Name);
                    break;
            }
            
            return View("Index", products);
        }

        
        [HttpGet]
        public async Task<IActionResult> Search(string keyword = "")
        {
            if (!keyword.IsNullOrEmpty())
            {
                var products = await _productService.Search(keyword);
                HttpContext.Session.SetObjectAsJson("RedirectProducts", products);
                return View("Index", products);
            }
            return RedirectToAction("Index", "Home");

        }

        public async Task<IActionResult> LikeProduct(int productId)
        {
            var user = await _userManager.GetUserAsync(User);
            Like like = new Like
            { 
                UserId = user.Id,
                ProductId = productId
            };
            await _productService.LikeProduct(like);

            return RedirectToAction("Index", "Home");
        }


    }
}

Controllers/WishlistController.cs
using ClothingStore.Models.Entity;
using ClothingStore.Models.Helper;
using ClothingStore.Models.Service.wishlist;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ClothingStore.Controllers
{
    [Authorize(Roles = "User")]
    public class WishlistController : Controller
    {
        private readonly IWishlistService _wishlistService;
        private readonly UserManager<User> _userManager;

        public WishlistController(IWishlistService wishlistService, UserManager<User> userManager)
        {
            _wishlistService = wishlistService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }


        public async Task<IActionResult> GetAll()
        {
            return View();
        }

        public async Task<IActionResult> AddToWishlist(int productId) 
        {
            var user = await _userManager.GetUserAsync(User);
            var wishList = new Wishlist
            {
                ProductId = productId,
                UserId = user.Id
            };
            await _wishlistService.AddAsync(wishList);

            var wishlists = await _wishlistService.GetAllAsync(user.Id);
            HttpContext.Session.SetObjectAsJson("Wishlists", wishlists);

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> RemoveFromWishlist(int productId)
        {
            // Xóa Wishlist khỏi Session
            var wishlist = HttpContext.Session.GetObjectFromJson<IEnumerable<Wishlist>>("Wishlists");
            var newWishlist = wishlist.Where(i => i.ProductId != productId);
            HttpContext.Session.SetObjectAsJson("Wishlists", newWishlist);

            // Xóa Wishlist khỏi Database
            var user = await _userManager.GetUserAsync(User);
            await _wishlistService.DeleteAsync(user.Id, productId);

            return RedirectToAction("Index", "Home");
        }

    }
}

Views/Home/Index.cshtml
@model IEnumerable<ClothingStore.Models.Entity.Product>
@using ClothingStore.Models.Service.product
@using ClothingStore.Models.Entity
@using Microsoft.AspNetCore.Identity

@inject IProductService _productService
@inject UserManager<User> _userManager
    
@{
    ViewData["Title"] = "Home Page";
    var manProducts = Model.Where(i => i.Gender.Equals("Nam") && i.Category.Name.Equals("Áo Polo")).ToList();
    var womenProducts = Model.Where(i => i.Gender.Equals("Nữ") && i.Category.Name.Equals("Quần Jean")).ToList();
    var user = await _userManager.GetUserAsync(User);
}

<partial name="../Component/_Banner" />

<div class="container">
    <div class="block my-5">
        <div class="block-title">
            <strong>Thời trang Nam</strong>
        </div>
        <div class="row block-body">
            @for(int i = 0; i < 4; i++)
            {
                <div class="col-3">
                    <div class="card p-0 shadow" style="width: 18rem;">
                        <img src="@manProducts[i].ProductImages[0].ImageUrl" class="card-img-top">
                        <div class="card-body px-4 align-items-">
                            <a class="card-title" style="min-height: 40px;" asp-controller="Product" asp-action="Detail" asp-route-productId="@manProducts[i].ProductId">@manProducts[i].Name</a>
                            <p class="card-text">@manProducts[i].UnitPrice VNĐ</p>
                            <div class="action d-flex justify-content-between">
                                <div>
                                    <a asp-controller="Product" asp-action="LikeProduct" asp-route-productId="@manProducts[i].ProductId">
                                        @if (_productService.IsLikeProduct(manProducts[i].ProductId, user.Id))
                                        {
                                            <i class="bi bi-hand-thumbs-up-fill"></i>
                                        }
                                        else
                                        {
                                            <i class="bi bi-hand-thumbs-up"></i>
                                        }

                                    </a>
                                </div>

                                <div>
                                    <a asp-controller="Wishlist" asp-action="AddToWishlist" asp-route-productId="@manProducts[i].ProductId"><i class="bi bi-heart icon"></i></a>

                                    <a asp-controller="ShoppingCart" asp-action="AddToShoppingCartFromProduct" asp-route-productId="@manProducts[i].ProductId"><i class="bi bi-cart3 icon"></i></a>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="text-center mt-4">
            <a asp-controller="Product" asp-action="Search" asp-route-keyword="Nam"  class="btn-readmore">XEM THÊM</a>
        </div>
    </div>  

    <div class="block my-5">
        <div class="block-title">
            <strong>Thời trang Nữ</strong>
        </div>
        <div class="row block-body">
            @for (int i = 0; i < 4; i++)
            {
                <div class="col-3">
                    <div class="card p-0 shadow" style="width: 18rem;">
                        <img src="@womenProducts[i].ProductImages[0].ImageUrl" class="card-img-top">
                        <div class="card-body px-4 align-items-">
                            <a class="card-title" style="min-height: 40px;" asp-controller="Product" asp-action="Detail" asp-route-productId="@womenProducts[i].ProductId">@womenProducts[i].Name</a>
                            <p class="card-text">@womenProducts[i].UnitPrice VNĐ</p>
                            <div class="action d-flex justify-content-between">
                                <div>
                                    <a asp-controller="Product" asp-action="LikeProduct" asp-route-productId="@womenProducts[i].ProductId">
                                        @if (_productService.IsLikeProduct(womenProducts[i].ProductId, user.Id))
                                        {
                                            <i class="bi bi-hand-thumbs-up-fill"></i>
                                        }
                                        else
                                        {
                                            <i class="bi bi-hand-thumbs-up"></i>
                                        }
                                    </a>
                                </div>
                                <div>
                                    <a asp-controller="Wishlist" asp-action="AddToWishlist" asp-route-productId="@womenProducts[i].ProductId"><i class="bi bi-heart icon"></i></a>

                                    <a asp-controller="ShoppingCart" asp-action="AddToShoppingCartFromProduct" asp-route-productId="@womenProducts[i].ProductId"><i class="bi bi-cart3 icon"></i></a>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="text-center mt-4">
            <a asp-controller="Product" asp-action="Search" asp-route-keyword="Nữ" class="btn-readmore">XEM THÊM</a>
        </div>
    </div>
</div>



<style>
    .icon {
        font-size: 22px;
        margin: 0px;
    }

    .block-title {
        margin: 0 auto 37px;
        position: relative;
        width: fit-content;
        text-align: center;
    }

    .block-title strong {
        display: inline-block;
        position: relative;
        font-size: 36px;
        font-weight: 700;
        text-transform: uppercase;
        z-index: 2;
    }

    .block-title:after {
        content: "";
        left: -17px;
        right: -17px;
        background: #e1e1e1;
        position: absolute;
        height: 10px;
        bottom: 10px;
    }

    .btn-readmore {
        display: inline-block;
        padding: 10px 20px !important;
        border: 1px black solid;
        font-weight: 700;
        border-radius: 10px;
    }

    .btn-readmore:hover {
        background-color: black;
        color: white;
    }

</style>